--add data table Tests
INSERT into Tests values ('IQ', N'Test IQ', 26, 1500)
INSERT into Tests values ('EQ', N'Test EQ', 10, 1200)
INSERT into Tests values ('IQTD', N'Test IQ Tuyển Dụng', 32, 4800)
INSERT into Tests values ('TC', N'Test Tính cách', 76, 6000)

--add data Question Test IQ
INSERT into Questions values ('IQ1', 'IQ', 1, 'IQ1.png')
INSERT into Questions values ('IQ2', 'IQ', 2, 'IQ2.png')
INSERT into Questions values ('IQ3', 'IQ', 3, 'IQ3.png')
INSERT into Questions values ('IQ4', 'IQ', 4, 'IQ4.png')
INSERT into Questions values ('IQ5', 'IQ', 5, 'IQ5.png')
INSERT into Questions values ('IQ6', 'IQ', 6, 'IQ6.png')
INSERT into Questions values ('IQ7', 'IQ', 7, 'IQ7.png')
INSERT into Questions values ('IQ8', 'IQ', 8, 'IQ8.png')
INSERT into Questions values ('IQ9', 'IQ', 9, 'IQ9.png')
INSERT into Questions values ('IQ10', 'IQ', 10, 'IQ10.png')
INSERT into Questions values ('IQ11', 'IQ', 11, 'IQ11.png')
INSERT into Questions values ('IQ12', 'IQ', 12, 'IQ12.png')
INSERT into Questions values ('IQ13', 'IQ', 13, 'IQ13.png')
INSERT into Questions values ('IQ14', 'IQ', 14, 'IQ14.png')
INSERT into Questions values ('IQ15', 'IQ', 15, 'IQ15.png')
INSERT into Questions values ('IQ16', 'IQ', 16, 'IQ16.png')
INSERT into Questions values ('IQ17', 'IQ', 17, 'IQ17.png')
INSERT into Questions values ('IQ18', 'IQ', 18, 'IQ18.png')
INSERT into Questions values ('IQ19', 'IQ', 19, 'IQ19.png')
INSERT into Questions values ('IQ20', 'IQ', 20, 'IQ20.png')
INSERT into Questions values ('IQ21', 'IQ', 21, 'IQ21.png')
INSERT into Questions values ('IQ22', 'IQ', 22, 'IQ22.png')
INSERT into Questions values ('IQ23', 'IQ', 23, 'IQ23.png')
INSERT into Questions values ('IQ24', 'IQ', 24, 'IQ24.png')
INSERT into Questions values ('IQ25', 'IQ', 25, 'IQ25.png')
INSERT into Questions values ('IQ26', 'IQ', 26, 'IQ26.png')

--add data Question Test EQ
INSERT into Questions values ('EQ1', 'EQ', 1, N'Bạn ở trên một chuyến bay và máy bay đột nhiên rung lắc dữ dội. Bạn sẽ làm gì?')
INSERT into Questions values ('EQ2', 'EQ', 2, N'Bạn đưa một nhóm trẻ 4 tuổi đến công viên, một bé gái trong số đó bắt đầu khóc bởi vì đám trẻ không chịu chơi với nó. Bạn sẽ làm gì?')
INSERT into Questions values ('EQ3', 'EQ', 3, N'Tưởng tượng rằng bạn là một sinh viên với một hy vọng nhỏ nhoi là được điểm A trong một môn học. Nhưng bạn vừa phát hiện ra là giữa kỳ được có C-. Bạn sẽ lam gì?')
INSERT into Questions values ('EQ4', 'EQ', 4, N'Tưởng tượng rằng bạn là một nhân viên bán bảo hiểm gọi điện cho các khách hàng tiềm năng của mình. 15 người liên tiếp cúp máy giữa chừng và bạn bắt đầu cảm thấy nản. Bạn sẽ làm gì?')
INSERT into Questions values ('EQ5', 'EQ', 5, N'Bạn là người quản lý trong một tổ chức kêu gọi cho sự bình đẳng chủng tộc và tôn giáo. Bạn tình cờ nghe được một người kể một câu chuyện hài phân biệt chủng tộc. Bạn sẽ làm gì?')
INSERT into Questions values ('EQ6', 'EQ', 6, N'Bạn đang cố gắng ngăn cản một người bạn cãi nhau với một người khác vì anh này vừa cắt ngang đầu xe của các bạn. Bạn sẽ làm gì?')
INSERT into Questions values ('EQ7', 'EQ', 7, N'Bạn và người bạn đời của mình cãi nhau và rồi to tiếng với nhau. Cả hai người đều đang rất ức chế, trong cơn nóng giận, các bạn đã xúc phạm nhau. Bạn nghĩ điều tốt nhất nên làm ở đây là gì?')
INSERT into Questions values ('EQ8', 'EQ', 8, N'Bạn được chỉ định lãnh đạo một nhóm đang cố tìm ra một phương pháp sáng tạo cho một vấn đề ở công ty. Đầu tiên bạn sẽ làm gì?')
INSERT into Questions values ('EQ9', 'EQ', 9, N'Đứa con trai 3 tuổi của bạn cực kỳ nhút nhát, đa cảm và pha lẫn một chú sợt sệt khi đến những nơi mới và trước người lạ hầu như từ khi mới sinh ra. Bạn sẽ làm gì?')
INSERT into Questions values ('EQ10', 'EQ', 10, N'Trong nhiều năm bạn muốn học lại một nhạc cụ mà bạn từng thử chơi khi còn bé. Bây giờ, vui là chính, bạn bắt đầu và bạn muốn sử dụng thời gian học một cách hiệu quả nhất. Bạn sẽ làm gì?')

--add data Question Test IQTD
INSERT into Questions values ('IQTD1', 'IQTD', 1, N'Điền số thích hợp vào dấu chấm hỏi : 0, 2, 4, ?, 8, ?, 12')	
INSERT into Questions values ('IQTD2', 'IQTD', 2, N'Tìm con vật khác biệt rõ rệt với những con còn lại: Cọp, mèo, khỉ, gấu trắng , chim cánh cụt, chim bồ câu.')
INSERT into Questions values ('IQTD3', 'IQTD', 3, N'Nếu TESTIQVN là NVQITSET thì 14715368 là:')
INSERT into Questions values ('IQTD4', 'IQTD', 4, N'Hiện nay Mark Zuckerberg 31 tuổi , 9 năm nữa tuổi anh ấy gấp đôi tuổi em gái mình hiện tại . Hỏi bây giờ tuổi em gái Mark là bao nhiêu ?')
INSERT into Questions values ('IQTD5', 'IQTD', 5, 'IQTD5.png')
INSERT into Questions values ('IQTD6', 'IQTD', 6, N'Một sản phẩm được hạ giá 60%, hỏi sản phẩm đó phải tăng giá lên bao nhiêu % để trở về giá ban đầu?')
INSERT into Questions values ('IQTD7', 'IQTD', 7, N'Số nào không thuộc dãy sau đây: 1, 1, 2, 3, 4, 5, 8, 13, 21')
INSERT into Questions values ('IQTD8', 'IQTD', 8, N'Nếu tất cả Ross là Hanoon và tất cả Hanoon là Oxy thì Ross là Oxy')
INSERT into Questions values ('IQTD9', 'IQTD', 9, N'Cái nào không cùng loại với những cái còn lại: Mặt Trời, sao Kim, sao băng, Mặt Trăng, ngôi sao, sao Hỏa.')
INSERT into Questions values ('IQTD10', 'IQTD', 10, N'Hai người cùng xuất phát ở một điểm, quay lưng vào nhau, cùng đi về phía trước 12m rồi rẽ trái 5m. Hỏi khoảng cách giữa 2 người lúc này là?')
INSERT into Questions values ('IQTD11', 'IQTD', 11, N'Nếu EGGFHGHE giống như 97786769 thì HEFGGHFE giống như')
INSERT into Questions values ('IQTD12', 'IQTD', 12, N'Bạn có 84 quả táo đựng trong 12 rổ, nếu muốn ăn 1/3 số táo trong mỗi rổ thì bạn cần ít nhất bao nhiêu lần cắn, biết rằng mỗi lần bạn cắn được 1/3 của 1/2 quả táo.')
INSERT into Questions values ('IQTD13', 'IQTD', 13, N'Nếu đọc ngược lại thì số 32247567597194 sẽ là số:')
INSERT into Questions values ('IQTD14', 'IQTD', 14, 'IQTD14.png')
INSERT into Questions values ('IQTD15', 'IQTD', 15, 'IQTD15.png')
INSERT into Questions values ('IQTD16', 'IQTD', 16, N'Hân thích số 25 nhưng không thích 24, thích 400 nhưng không thích 300, thích 144 nhưng không thích 145. Hỏi Hân sẽ thích số nào sau đây:')
INSERT into Questions values ('IQTD17', 'IQTD', 17, 'IQTD17.png')
INSERT into Questions values ('IQTD18', 'IQTD', 18, 'IQTD18.png')
INSERT into Questions values ('IQTD19', 'IQTD', 19, N'8 người sơn được 3 cái nhà trong 6 giờ. Hỏi với 12 người sẽ sơn được bao nhiêu cái nhà trong 12 giờ?')
INSERT into Questions values ('IQTD20', 'IQTD', 20, N'Số nào không thuộc dãy sau đây: 13, 15, 17, 19')
INSERT into Questions values ('IQTD21', 'IQTD', 21, 'IQTD21.png')
INSERT into Questions values ('IQTD22', 'IQTD', 22, 'IQTD22.png')
INSERT into Questions values ('IQTD23', 'IQTD', 23, 'IQTD23.png')
INSERT into Questions values ('IQTD24', 'IQTD', 24, 'IQTD24.png')
INSERT into Questions values ('IQTD25', 'IQTD', 25, N'Lan hôm nay đi chợ lần đầu, mẹ cô dặn mua cho bà một ít quả LÊ và với số tiền cho trước là 23 000 đồng. Hỏi với số tiền được cho, Lan mua được nhiều nhất mấy quả LÊ? Biết rằng: +) TÁO + TÁO + LÊ+ ĐÀO = 23 000 đồng +) ĐÀO + TÁO + CAM+ TÁO = 22 000 đồng +) TÁO + CAM + TÁO + TÁO = 16 000 đồng +) TÁO + TÁO + TÁO + TÁO =12 000 đồng')
INSERT into Questions values ('IQTD26', 'IQTD', 26, N'Điền vào chỗ trống: A, D, A, E, I, ?, F, ?, C, E')
INSERT into Questions values ('IQTD27', 'IQTD', 27, 'IQTD27.png')
INSERT into Questions values ('IQTD28', 'IQTD', 28, 'IQTD28.png')
INSERT into Questions values ('IQTD29', 'IQTD', 29, 'IQTD29.png')
INSERT into Questions values ('IQTD30', 'IQTD', 30, 'IQTD30.png')
INSERT into Questions values ('IQTD31', 'IQTD', 31, 'IQTD31.png')
INSERT into Questions values ('IQTD32', 'IQTD', 32, 'IQTD32.png')

--add data Question Test Tich cach
INSERT into Questions values ('TC1', 'TC', 1, N'Bạn thích công việc kiểu :')
INSERT into Questions values ('TC2', 'TC', 2, N'Bạn tiếp xúc với một người theo xu hướng :')
INSERT into Questions values ('TC3', 'TC', 3, N'Bạn đánh giá sự việc dựa trên :')
INSERT into Questions values ('TC4', 'TC', 4, N'Bạn là người có tác phong :')
INSERT into Questions values ('TC5', 'TC', 5, N'Trong các cuộc giao tiếp, bạn là người :')
INSERT into Questions values ('TC6', 'TC', 6, N'Bạn là người thế nào :')
INSERT into Questions values ('TC7', 'TC', 7, N'Tính cách của bạn :')
INSERT into Questions values ('TC8', 'TC', 8, N'Những người có tầm nhìn xa thường :')
INSERT into Questions values ('TC9', 'TC', 9, N'Đối với những người mới gặp, bàn thường :')
INSERT into Questions values ('TC10', 'TC', 10, N'Một công việc gây nhàm chán khi:')
INSERT into Questions values ('TC11', 'TC', 11, N'Bạn bị hấp dẫn bởi :')
INSERT into Questions values ('TC12', 'TC', 12, N'Bạn bị lôi cuốn bởi kiểu người :')
INSERT into Questions values ('TC13', 'TC', 13, N'Trong các cuộc trò chuyện bạn thường :')
INSERT into Questions values ('TC14', 'TC', 14, N'Lựa chọn của bạn có xu hướng :')
INSERT into Questions values ('TC15', 'TC', 15, N'Trong hai điều sau, điều nào tồi tệ hơn:')
INSERT into Questions values ('TC16', 'TC', 16, N'Tính cách nào giống bạn hơn :')
INSERT into Questions values ('TC17', 'TC', 17, N'Đối với một vấn đề trong nhóm :')
INSERT into Questions values ('TC18', 'TC', 18, N'Trong cuộc sống, bạn cảm thấy hứng thú với :')
INSERT into Questions values ('TC19', 'TC', 19, N'Bạn thấy tâm đắc với bản thân bởi sự')
INSERT into Questions values ('TC20', 'TC', 20, N'Bạn nhìn nhận một vấn đề với :')
INSERT into Questions values ('TC21', 'TC', 21, N'Trong các kỳ nghỉ lễ bạn có xu hướng :')
INSERT into Questions values ('TC22', 'TC', 22, N'Bạn bị lôi cuốn bởi :')
INSERT into Questions values ('TC23', 'TC', 23, N'Khi quyết định việc gì bạn thường dựa vào :')
INSERT into Questions values ('TC24', 'TC', 24, N'Bạn thích làm việc với người Sếp :')
INSERT into Questions values ('TC25', 'TC', 25, N'Bạn nghiêng về :')
INSERT into Questions values ('TC26', 'TC', 26, N'Bạn là người có tư tưởng :')
INSERT into Questions values ('TC27', 'TC', 27, N'Bạn thích học các môn :')
INSERT into Questions values ('TC28', 'TC', 28, N'Trong một nhóm bạn bè bạn thường :')
INSERT into Questions values ('TC29', 'TC', 29, N'Khi đánh giá một người bạn thường :')
INSERT into Questions values ('TC30', 'TC', 30, N'Sẽ thật tai hại khi bạn :')
INSERT into Questions values ('TC31', 'TC', 31, N'Phong cách của bạn :')
INSERT into Questions values ('TC32', 'TC', 32, N'Khi giải quyết một công việc thông thường, bạn sẽ :')
INSERT into Questions values ('TC33', 'TC', 33, N'Bạn thích làm việc :')
INSERT into Questions values ('TC34', 'TC', 34, N'Bạn có hành động theo bản năng :')
INSERT into Questions values ('TC35', 'TC', 35, N'Trong cuộc sống, một người sẽ tốt hơn nếu :')
INSERT into Questions values ('TC36', 'TC', 36, N'Khi nghe một album nhạc mới, bạn thường nghe :')
INSERT into Questions values ('TC37', 'TC', 37, N'Bạn là người :')
INSERT into Questions values ('TC38', 'TC', 38, N'Sẽ khó khăn hơn khi bạn cố:')
INSERT into Questions values ('TC39', 'TC', 39, N'Khi trình bày bạn thường :')
INSERT into Questions values ('TC40', 'TC', 40, N'Khi cảm thấy buồn bạn thường :')
INSERT into Questions values ('TC41', 'TC', 41, N'Đối với các hoạt động của cơ quan, lớp học :')
INSERT into Questions values ('TC42', 'TC', 42, N'Bạn cảm thấy thoái mái với :')
INSERT into Questions values ('TC43', 'TC', 43, N'Cảm xúc của bạn thường được người khác :')
INSERT into Questions values ('TC44', 'TC', 44, N'Thật tồi tệ khi :')
INSERT into Questions values ('TC45', 'TC', 45, N'Bạn muốn một sự kiện như thế nào :')
INSERT into Questions values ('TC46', 'TC', 46, N'Bạn là người có tình cách :')
INSERT into Questions values ('TC47', 'TC', 47, N'Bạn có ưu điểm về :')
INSERT into Questions values ('TC48', 'TC', 48, N'Khi quyết định điều gì đó, bạn tin vào :')
INSERT into Questions values ('TC49', 'TC', 49, N'Bạn muốn được người khác khen ngợi như thế nào :')
INSERT into Questions values ('TC50', 'TC', 50, N'Bạn thích các sự việc xảy ra :')
INSERT into Questions values ('TC51', 'TC', 51, N'Bạn hay hành động một cách :')
INSERT into Questions values ('TC52', 'TC', 52, N'Bạn muốn bổ sung thêm điều gì ở bản thân :')
INSERT into Questions values ('TC53', 'TC', 53, N'Bạn là người :')
INSERT into Questions values ('TC54', 'TC', 54, N'Khi điện thoại bàn trong văn phòng công ty đổ chuông :')
INSERT into Questions values ('TC55', 'TC', 55, N'Bạn mới tham gia một lớp Ngoại ngữ :')
INSERT into Questions values ('TC56', 'TC', 56, N'Theo bạn, các sự việc, sự kiện :')
INSERT into Questions values ('TC57', 'TC', 57, N'Bạn là người :')
INSERT into Questions values ('TC58', 'TC', 58, N'Bạn thường quan tâm tới người khác thông qua :')
INSERT into Questions values ('TC59', 'TC', 59, N'Bạn nghiêng về điều nào sau đây :')
INSERT into Questions values ('TC60', 'TC', 60, N'Mọi việc sẽ tôt hơn nếu :')
INSERT into Questions values ('TC61', 'TC', 61, N'Bạn thích mối quan hệ :')
INSERT into Questions values ('TC62', 'TC', 62, N'Nếu bạn là nhà văn, bạn sẽ viết bài theo cách :')
INSERT into Questions values ('TC63', 'TC', 63, N'Khi quyết định một việc :')
INSERT into Questions values ('TC64', 'TC', 64, N'Bạn thường hay đưa ra quyết định :')
INSERT into Questions values ('TC65', 'TC', 65, N'Bạn là người sống thiên về :')
INSERT into Questions values ('TC66', 'TC', 66, N'Bạn thích thú với sự việc :')
INSERT into Questions values ('TC67', 'TC', 67, N'Khi nói về một chủ đề mới lạ chưa gặp, bạn cảm thấy :')
INSERT into Questions values ('TC68', 'TC', 68, N'Đối với một suy luận được nhiều người tin dùng, bạn sẽ :')
INSERT into Questions values ('TC69', 'TC', 69, N'Điều gì làm cho bạn ấn tượng :')
INSERT into Questions values ('TC70', 'TC', 70, N'Bạn là người có xu hướng thiên về :')
INSERT into Questions values ('TC71', 'TC', 71, N'Ở một nơi đông người làm bạn :')
INSERT into Questions values ('TC72', 'TC', 72, N'Bạn đánh giá một người dựa trên :')
INSERT into Questions values ('TC73', 'TC', 73, N'Bạn được mời tới bữa tiệc của công ty :')
INSERT into Questions values ('TC74', 'TC', 74, N'Khi làm việc bạn sẽ :')
INSERT into Questions values ('TC75', 'TC', 75, N'Khi đi tham dự một buổi liên hoan/tiệc tùng, bạn sẽ :')
INSERT into Questions values ('TC76', 'TC', 76, N'Điều gì làm bạn cảm thấy tồi tệ :')

--add data Answer Test IQ
declare @MaCHoi varchar(8);
declare @DAn1 varchar(20);
declare @DAn2 varchar(20);
declare @DAn3 varchar(20);
declare @DAn4 varchar(20);
declare @DAn5 varchar(20);
declare @DAn6 varchar(20);
declare @i int = 1;
declare @j varchar(3);

while @i <= 26
begin
	set @j = CAST(@i as varchar);
	set @MaCHoi = 'IQ' + @j;
	set @DAn1 = @MaCHoi + '-1.png';
	set @DAn2 = @MaCHoi + '-2.png';
	set @DAn3 = @MaCHoi + '-3.png';
	set @DAn4 = @MaCHoi + '-4.png';
	set @DAn5 = @MaCHoi + '-5.png';
	set @DAn6 = @MaCHoi + '-6.png';
	set @i = @i + 1;
	insert into Answers values (@MaCHoi,'',@DAn1, @DAn2, @DAn3, @DAn4, @DAn5, @DAn6)
end

--add data Answer Test EQ
insert into Answers values ('EQ1', '', N'Tiếp tục đọc sách, xem phim, nghe nhạc,…. Nói chung không quan tâm.', N'Trở nên thận trọng, cẩn thận nghe các tiếp viên hàng không hướng dẫn trong trường hợp khẩn cấp.', N'Một chút từ cả A và B.', N'Không biết nữa.', null, null)
insert into Answers values ('EQ2', '', N'Đứng ngoài và để bọn trẻ tự giải quyết.', N'Nói chuyện với cô bé và tìm cách để đám trẻ kia chơi chung với bạn mình.', N'Nhẹ nhàng bảo cô bé nín khóc.', N'Chỉ cho cô bé những thứ khác mà cô bé có thể chơi.', null, null)
insert into Answers values ('EQ3', '', N'Lập ra một kế hoạch học tập cụ thể nhằm cải thiện điểm và quyết tâm thực hiện nó.', N'Quyết tâm làm tốt hơn trong tương lai.', N'Bảo với bản thân rằng chả sao cả, thay vào đó bạn sẽ tập trung vào những lớp có điểm số khá hơn.', N'Thuyết phục thầy giáo để có điểm số tốt hơn.', null, null)
insert into Answers values ('EQ4', '', N'Thế là đủ cho ngày hôm nay và hy vọng ngày mai sẽ tươi sáng hơn.', N'b.	Đánh giá những khuyết điểm của mình và tìm ra những cái mà bạn cho rằng đã phá hoại cuộc trò chuyện.', N'Thử một cách tiếp cận mới trong cuộc gọi kế và luôn luôn cố gắng.', N'Cân nhắc tìm một công việc khác.', null, null)
insert into Answers values ('EQ5', '', N'Kệ. Đùa thôi mà.', N'Gọi người đó vào văn phòng và quở trách.', N'Can thiệp ngay lập tức, bảo rằng câu chuyện đó không phù hợp ở đây và hành động này sẽ không được bỏ qua trong tổ chức bạn quản lý.', N'Bảo người đó tham dự một khóa đào tạo về sự bình đẳng.', null, null)
insert into Answers values ('EQ6', '', N'Bảo anh ấy quên đi, chẳng có ai bị thương cả và chuyện nào không có gì to tát.', N'Bật các bài hát anh ấy thích để “hạ hỏa”.', N'Cùng với anh ấy gây lộn với người tài xế kia.', N'Kể với anh ấy rằng bạn cũng đã ở trong trường hợp này và bạn cũng tức giận như vậy nhưng rồi  bạn thấy người tài xế đó đang trên đường tới phòng cấp cứu.', null, null)
insert into Answers values ('EQ7', '', N'Nghỉ 20 phút rồi tiếp tục nói chuyện với nhau.', N'Dừng vụ cãi nhau và giữ im lặng mặc cho người kia nói gì.', N'Bảo rằng bạn xin lỗi nhưng người kia cũng phải xin lỗi bạn.', N'Dừng một lúc, suy nghĩ thât thấu đáo và nêu rõ quan điểm của mình trong vụ việc.', null, null)
insert into Answers values ('EQ8', '', N'Vẽ ra một lịch trình làm việc và dành nhiều thời gian thảo luận ở từng mục nhằm sử dụng tốt nhất khoảng thời gian làm việc.', N'Cho mọi người thời gian để tìm hiểu lẫn nhau.', N'Bắt đầu hỏi ý kiến mọi người về vấn đề khi ý tưởng vẫn còn mới.', null, null, null)
insert into Answers values ('EQ9', '', N'Chấp nhận rằng con mình có bản tính nhút nhát và nghĩ cách che chở nó khỏi những thứ ấy.', N'Dẫn nó đi bác sĩ tâm lý.', N'Dẫn nó đi đến những nơi lạ và gặp gỡ mọi người để giúp con mình vượt qua nỗi sợ.', N'Thiết kế một chuỗi những thử thách đem đến những trải nghiệm mà sẽ dạy con bạn cách đối phó với nỗi sợ.', null, null)
insert into Answers values ('EQ10', '', N'Đưa mình vào một thời khóa biểu nghiêm túc mỗi ngày.', N'Chọn những phần nâng cao kỹ năng một chút.', N'Chỉ luyện tập khi có hứng.', N'Chọn phần mà vượt quá khả năng của mình, nhưng bạn có thể vượt qua nếu nỗ lực.', null, null)

--add data Answer Test IQTD
insert into Answers values ('IQTD1', '', N'5, 9', N'7, 8', N'8, 11', N'6, 10', N'6, 11', N'5, 10')
insert into Answers values ('IQTD2', '', N'Cọp', N'Mèo', N'Khỉ', N'Gấu Trắng', N'Chim cánh cụt', N'Chim bồ câu')
insert into Answers values ('IQTD3', '', N'863511241', N'86351741', N'86351714', N'86331741', N'68537114', N'88351741')
insert into Answers values ('IQTD4', '', N'20', N'21', N'22', N'23', N'24', N'25')
insert into Answers values ('IQTD5', '', N'IQTD5-1.png', N'IQTD5-2.png', N'IQTD5-3.png', N'IQTD5-4.png', N'IQTD5-5.png', N'IQTD5-6.png')
insert into Answers values ('IQTD6', '', N'50%', N'60%', N'66.67%', N'53.33%', N'100%', N'150%')
insert into Answers values ('IQTD7', '', N'1', N'2', N'3', N'4', N'5', N'8')
insert into Answers values ('IQTD8', '', N'Đúng', N'Sai', N'Có thể đúng hoặc sai', N'Tôi không biết hoặc đáp án khác', null, null)
insert into Answers values ('IQTD9', '', N'Mặt Trời', N'Sao Kim', N'Sao Băng', N'Mặt Trăng', N'Ngôi sao', N'Sao Hỏa')
insert into Answers values ('IQTD10', '', N'10', N'13', N'16', N'20', N'23', N'26')
insert into Answers values ('IQTD11', '', N'69876988', N'69877698', N'69877689', N'68967989', N'69877698', N'68966987')
insert into Answers values ('IQTD12', '', N'108 lần', N'121 lần', N'144 lần', N'168 lần', N'196 lần', N'225 lần')
insert into Answers values ('IQTD13', '', N'49179576574224', N'49179567752132', N'49179576574223', N'49175975764223', N'49179576574232', N'49179565574223')
insert into Answers values ('IQTD14', '', N'IQTD14-1.png', N'IQTD14-2.png', N'IQTD14-3.png', N'IQTD14-4.png', N'IQTD14-5.png', N'IQTD14-6.png')
insert into Answers values ('IQTD15', '', N'IQTD15-1.png', N'IQTD15-2.png', N'IQTD15-3.png', N'IQTD15-4.png', N'IQTD15-5.png', N'IQTD15-6.png')
insert into Answers values ('IQTD16', '', N'10', N'50', N'124', N'200', N'1600', N'2000')
insert into Answers values ('IQTD17', '', N'IQTD17-1.png', N'IQTD17-2.png', N'IQTD17-3.png', N'IQTD17-4.png', N'IQTD17-5.png', N'IQTD17-6.png')
insert into Answers values ('IQTD18', '', N'IQTD18-1.png', N'IQTD18-2.png', N'IQTD18-3.png', N'IQTD18-4.png', N'IQTD18-5.png', N'IQTD18-6.png')
insert into Answers values ('IQTD19', '', N'3 cái', N'5 cái', N'7 cái', N'8 cái', N'9 cái', N'10 cái')
insert into Answers values ('IQTD20', '', N'13', N'15', N'17', N'179', null, null)
insert into Answers values ('IQTD21', '', N'IQTD21-1.png', N'IQTD21-2.png', N'IQTD21-3.png', N'IQTD21-4.png', N'IQTD21-5.png', N'IQTD21-6.png')
insert into Answers values ('IQTD22', '', N'IQTD22-1.png', N'IQTD22-2.png', N'IQTD22-3.png', N'IQTD22-4.png', null, null)
insert into Answers values ('IQTD23', '', N'IQTD23-1.png', N'IQTD23-2.png', N'IQTD23-3.png', N'IQTD23-4.png', N'IQTD23-5.png', N'IQTD23-6.png')
insert into Answers values ('IQTD24', '', N'IQTD24-1.png', N'IQTD24-2.png', N'IQTD24-3.png', N'IQTD24-4.png', null, null)
insert into Answers values ('IQTD25', '', N'2 quả', N'4 quả', N'6 quả', N'8 quả', N'10 quả', N'12 quả')
insert into Answers values ('IQTD26', '', N'A, F', N'A, D', N'B, F', N'A, D', N'A, C', N'B, E')
insert into Answers values ('IQTD27', '', N'IQTD27-1.png', N'IQTD27-2.png', N'IQTD27-3.png', N'IQTD27-4.png', N'IQTD27-5.png', N'IQTD27-6.png')
insert into Answers values ('IQTD28', '', N'IQTD28-1.png', N'IQTD28-2.png', N'IQTD28-3.png', N'IQTD28-4.png', N'IQTD28-5.png', N'IQTD28-6.png')
insert into Answers values ('IQTD29', '', N'IQTD29-1.png', N'IQTD29-2.png', N'IQTD29-3.png', N'IQTD29-4.png', N'IQTD29-5.png', N'IQTD29-6.png')
insert into Answers values ('IQTD30', '', N'IQTD30-1.png', N'IQTD30-2.png', N'IQTD30-3.png', N'IQTD30-4.png', N'IQTD30-5.png', N'IQTD30-6.png')
insert into Answers values ('IQTD31', '', N'IQTD31-1.png', N'IQTD31-2.png', N'IQTD31-3.png', N'IQTD31-4.png', N'IQTD31-5.png', N'IQTD31-6.png')
insert into Answers values ('IQTD32', '', N'IQTD32-1.png', N'IQTD32-2.png', N'IQTD32-3.png', N'IQTD32-4.png', N'IQTD32-5.png', N'IQTD32-6.png')

--add data Answer Test TC
insert into Answers values ('TC1', '', N'Xã hội, giao tiếp.', N'Thiết kế, nghiên cứu.', null, null, null, null)
insert into Answers values ('TC2', '', N'Khách quan.', N'Chủ quan.', null, null, null, null)
insert into Answers values ('TC3', '', N'Ý nghĩa, giá trị.', N'Tính logic.', null, null, null, null)
insert into Answers values ('TC4', '', N'Thong thả, thoải mái.', N'Nhanh nhẹn, đúng giờ.', null, null, null, null)
insert into Answers values ('TC5', '', N'Bắt đầu cho cuộc nói chuyện.', N'Chỉ nói khi người khác bắt chuyện.', null, null, null, null)
insert into Answers values ('TC6', '', N'Là người có cái đầu lạnh.', N'Là người có trái tim ấm.', null, null, null, null)
insert into Answers values ('TC7', '', N'Dễ chịu, thoải mái.', N'Nghiêm chỉnh, quả quyết.', null, null, null, null)
insert into Answers values ('TC8', '', N'Khá thú vị.', N'Khó hiểu', null, null, null, null)
insert into Answers values ('TC9', '', N'Dễ dàng bắt chuyện và trò chuyện nhiều điều cùng họ.', N'Cảm thấy khó khăn và không biết nên nói gì.', null, null, null, null)
insert into Answers values ('TC10', '', N'Không có quy trình cụ thể.', N'Thiếu tính sáng tạo.', null, null, null, null)
insert into Answers values ('TC11', '', N'Sự hòa hợp với mọi người.', N'Sự nhất quán trong suy nghĩ', null, null, null, null)
insert into Answers values ('TC12', '', N'Giàu trí tưởng tượng.', N'Nắm bắt tình huống tốt.', null, null, null, null)
insert into Answers values ('TC13', '', N'Dè dặt.', N'THoải mái.', null, null, null, null)
insert into Answers values ('TC14', '', N'Tuân theo chuẩn mực.', N'Đôi lúc không hiểu rõ nguyên nhân.', null, null, null, null)
insert into Answers values ('TC15', '', N'Không công bằng.', N'Tàn nhẫn.', null, null, null, null)
insert into Answers values ('TC16', '', N'Kiên quyết.', N'Nhẹ nhàng.', null, null, null, null)
insert into Answers values ('TC17', '', N'Độc lập giải quyết.', N'Trao đổi với mọi người.', null, null, null, null)
insert into Answers values ('TC18', '', N'Những điều bất ngờ không tính trước.', N'Những điều có kế hoặch trước.', null, null, null, null)
insert into Answers values ('TC19', '', N'Chắc chắn torng tư tưởng.', N'Cống hiến hết mình.', null, null, null, null)
insert into Answers values ('TC20', '', N'Khả năng lý luận phân tích.', N'Sự liên tưởng.', null, null, null, null)
insert into Answers values ('TC21', '', N'Ở nhà cùng gia đình.', N'Đi du lịch cùng bạn bè.', null, null, null, null)
insert into Answers values ('TC22', '', N'Các ngụ ý, hàm ý, ẩn ý.', N'Các nguyên tắc, nguyên lý.', null, null, null, null)
insert into Answers values ('TC23', '', N'Cảm nhận từ con tim.', N'Những quy tắc chung.', null, null, null, null)
insert into Answers values ('TC24', '', N'Làm việc có phương pháp, tổ chức tốt.', N'Ứng biến xoay trở tốt trước khó khăn.', null, null, null, null)
insert into Answers values ('TC25', '', N'Sự chắc chắn.', N'Sự cởi mở.', null, null, null, null)
insert into Answers values ('TC26', '', N'Công tư phân minh.', N'Bị tình cảm chi phối.', null, null, null, null)
insert into Answers values ('TC27', '', N'Nghệ thuật.', N'Khoa học.', null, null, null, null)
insert into Answers values ('TC28', '', N'Trầm lặng, ít nói.', N'Hoạt bát, vui vẻ.', null, null, null, null)
insert into Answers values ('TC29', '', N'Dựa vào vẻ ngoài của họ.', N'Dựa vào cảm nhận của bạn', null, null, null, null)
insert into Answers values ('TC30', '', N'Quá nồng nhiệt, mong chờ.', N'Quá khách quan.', null, null, null, null)
insert into Answers values ('TC31', '', N'Thích những thứ quen thuộc.', N'Thích những điều mới mẻ.', null, null, null, null)
insert into Answers values ('TC32', '', N'Tìm kiếm một cách làm mới.', N'Làm theo cách mọi người hay làm.', null, null, null, null)
insert into Answers values ('TC33', '', N'Độc lập.', N'Theo nhóm.', null, null, null, null)
insert into Answers values ('TC34', '', N'Hiếm khi.', N'Hay xảy ra.', null, null, null, null)
insert into Answers values ('TC35', '', N'Giàu lý trí.', N'Giàu cảm xúc.', null, null, null, null)
insert into Answers values ('TC36', '', N'Theo thứ tự.', N'Phát ngẫu nhiên.', null, null, null, null)
insert into Answers values ('TC37', '', N'Khéo léo, lanh lợi.', N'Thẳng thắn, thực tế', null, null, null, null)
insert into Answers values ('TC38', '', N'Sử dụng người khác.', N'Hiểu và chia sẻ với người khác.', null, null, null, null)
insert into Answers values ('TC39', '', N'Diễn đạt trực tiếp nhất có thể.', N'Diễn đạt một cách gián tiếp.', null, null, null, null)
insert into Answers values ('TC40', '', N'Tìm bạn bè tâm sự hoặc đi chơi.', N'Muốn ở một mình cho khuây khỏa.', null, null, null, null)
insert into Answers values ('TC41', '', N'Tham gia khi bị ép.', N'Năng nổ, tích cực.', null, null, null, null)
insert into Answers values ('TC42', '', N'Những thứ không xác định.', N'Những thứ có logic.', null, null, null, null)
insert into Answers values ('TC43', '', N'Dễ dàng nắm bắt.', N'Giấu kín, khó nhận biết.', null, null, null, null)
insert into Answers values ('TC44', '', N'Hành xử thiếu cân nhắc.', N'Chỉ trích, phê phán người khác.', null, null, null, null)
insert into Answers values ('TC45', '', N'Chuẩn bị chu toàn trước.', N'Diễn ra tự nhiên.', null, null, null, null)
insert into Answers values ('TC46', '', N'Dễ gần, hòa đồng.', N'Thân thiện nhưng kín đáo.', null, null, null, null)
insert into Answers values ('TC47', '', N'Trí tưởng tượng phong phú.', N'Sự quan sát thực tế.', null, null, null, null)
insert into Answers values ('TC48', '', N'Linh cảm.', N'Sự việc thực tế.', null, null, null, null)
insert into Answers values ('TC49', '', N'Bạn là người có đầu óc suy luận.', N'Bạn là người giàu tình cảm và sự tinh tế.', null, null, null, null)
insert into Answers values ('TC50', '', N'Có chọn lựa và suy tính.', N'Một cách tự nhiên', null, null, null, null)
insert into Answers values ('TC51', '', N'Bộc phát, linh hoạt.', N'Kỹ lưỡng, cẩn thận.', null, null, null, null)
insert into Answers values ('TC52', '', N'Tình cảm dồi dào.', N'Lý trí mạnh mẽ.', null, null, null, null)
insert into Answers values ('TC53', '', N'Mơ mộng và tưởng tượng.', N'Thực tế và thực dụng.', null, null, null, null)
insert into Answers values ('TC54', '', N'Nhấc máy trước để nghe.', N'Để cho đồng nghiệp nhấc máy.', null, null, null, null)
insert into Answers values ('TC55', '', N'Cố làm quen với nhiều người.', N'Chỉ nói chuyện với vài người.', null, null, null, null)
insert into Answers values ('TC56', '', N'Bản thân nó giải thích cho chính nó.', N'Là bằng chứng giải thích cho các quy tắc, quy luật.', null, null, null, null)
insert into Answers values ('TC57', '', N'Đa sầu đa cảm.', N'Thực dụng, không bị chi phối bởi tình cảm.', null, null, null, null)
insert into Answers values ('TC58', '', N'Những suy nghĩ của họ.', N'Những gì họ làm được.', null, null, null, null)
insert into Answers values ('TC59', '', N'Thói quen.', N'Những điều mới mẻ.', null, null, null, null)
insert into Answers values ('TC60', '', N'Luôn được chuẩn bị kỹ lưỡng.', N'Tùy cơ ứng biến.', null, null, null, null)
insert into Answers values ('TC61', '', N'Ít bạn nhưng chơi rất thân.', N'Nhiều bạn nhưng không thân thiết lắm.', null, null, null, null)
insert into Answers values ('TC62', '', N'Diễn đạt lời văn qua các phép so sánh, ẩn dụ.', N'Nghĩ sao viết vậy, diễn đạt rõ ràng.', null, null, null, null)
insert into Answers values ('TC63', '', N'Phụ thuộc vào tâm trạng.', N'Suy tính cẩn trọng.', null, null, null, null)
insert into Answers values ('TC64', '', N'Một cách chắc chắn.', N'Không chắc lắm, có thể thay đổi sau.', null, null, null, null)
insert into Answers values ('TC65', '', N'Nguyên tắc, lý trí.', N'Cảm xúc, tình cảm.', null, null, null, null)
insert into Answers values ('TC66', '', N'Thực tế.', N'Bất ngờ, mới mẻ.', null, null, null, null)
insert into Answers values ('TC67', '', N'Không hứng thú.', N'Hào hứng.', null, null, null, null)
insert into Answers values ('TC68', '', N'Kiểm tra lại trước khi áp dụng.', N'Tin tưởng và áp dụng theo.', null, null, null, null)
insert into Answers values ('TC69', '', N'Những thứ có tính logic cao.', N'Những thứ gây cảm động.', null, null, null, null)
insert into Answers values ('TC70', '', N'Những thứ thực tế và rõ ràng.', N'Những suy đoán.', null, null, null, null)
insert into Answers values ('TC71', '', N'Không thoải mái.', N'Thích thú.', null, null, null, null)
insert into Answers values ('TC72', '', N'Hoàn cảnh nhất định.', N'Nguyên tắc chung.', null, null, null, null)
insert into Answers values ('TC73', '', N'Ra về sớm vì không hào hứng lắm.', N'Vui chơi hết mình cho đến khi tàn tiệc.', null, null, null, null)
insert into Answers values ('TC74', '', N'Tuân thủ thời gian.', N'Làm việc tùy hứng.', null, null, null, null)
insert into Answers values ('TC75', '', N'Trò chuyện cùng nhiều người, quen hoặc không quen.', N'Chỉ trò chuyện với một số người quen.', null, null, null, null)
insert into Answers values ('TC76', '', N'Những thứ mơ hồ, không rõ ràng.', N'Những thứ nhàm chán, tẻ nhạt.', null, null, null, null)
